### ISSUE TITLE
Navigation links temporarily set wrong

### ISSUE THREAD

**Issue by trlkly** [Questionable-Content-Extensions/client#12]
On first load of a new page, I notice that the navigation link targets get set to http://www.questionablecontent.net/view.php?comic= until the script fully loads. Only then do they get changed back to the proper URLs.

This causes any attempt to click them during this time to take the user to a 404 page. 

I don't see why there's any reason to change the links at all until the script is completely loaded. Worst case scenario, they abort loading of the script and load a whole new page. 

(To be honest, I'm not sure why the script changes the link targets at all. Can't you just add the `ng-click` part without changing the target?)

**Comment by ilyvion** [comment]
Not sure why I never noticed this issue, I usually get an email when issues are made/commented on. Anyway, for anyone coming by, the rationale behind this behavior is explained in #13, and both this issue and that one will be fixed at the same time once I fix the underlying problem.

**Comment by trlkly** [comment]
Let me know when you release this, and I'll confirm that this fixes this issue, too.

**Comment by ilyvion** [comment]
A release has been made, it will either update automatically at some point, or you may have to manually trigger one. The latest released version is 0.4.1.

**Comment by trlkly** [comment]
The [meta for the script](https://questionablextensions.net/releases/qc-ext.latest.meta.js) hasn't updated, so the script won't update (automatically or manually). Only downloading the script again (from the main website) allows me to update.

I do confirm that version 0.4.1 fixes this bug, however.

**Comment by ilyvion** [comment]
The meta is definitely updated. When I look at it, it says 0.4.1 in the @**version** field. Maybe it's a caching issue in your browser (or in a cache between you and my server).

**Comment by trlkly** [comment]
It'd be a weird caching issue where the main file was updated, but the meta file was not. 

Still, it is indeed updated now. I'll assume a 24 hour delay in the future.

**Comment by ilyvion** [comment]
Well no, it's not that strange, since your browser is probably polling the meta file regularly (to check if there's an update), but leaving the main file alone between updates, letting its cache data expire between updates.

Still, I could try to disable caching for the meta file in the future, so that browsers shouldn't hold on to old information about it.

**Comment by trlkly** [comment]
True. But it still sounds like a possible issue on your end. The update feature would be pointless if it uses the cache by default. It's going to poll the site, and only pull it from the cache if the server says the file has not been updated. 

Though just disabling caching would fix that, too.
