### ISSUE TITLE
Search by character(s)/location(s)

### ISSUE THREAD

**Issue by Nixill** [Questionable-Content-Extensions/client#15]
It'd be a neat feature to have if you could search by character(s) or location(s) in a comic.

**Comment by ilyvion** [comment]
This feature is almost implemented, actually. I just got severely demotivated because somebody told me I was making it [too complicated](http://i.imgur.com/ABVv2vi.png). So I took a long break from the whole thing.

**Comment by Nixill** [comment]
Maybe have it two ways:

1. Enter a list of characters or locations (with autocomplete) and two switches or pairs of radio buttons - one for "Any of these characters (require all if unchecked)" (default unchecked) and one for "Any of these locations (require all if unchecked)" (default checked).
2. Advanced search: The way you did it in the picture.

**Comment by ilyvion** [comment]
This feature will be in the next release (1.2); it ended up working like this:
![image](https://github.com/Questionable-Content-Extensions/client/assets/767490/9c084ef6-74da-457d-a8ca-9443549b51f8)
