### ISSUE TITLE
Extension breaks Alt-Left

### ISSUE THREAD

**Issue by thirtythreeforty** [Questionable-Content-Extensions/client#2]
This plugin is great!  There is one minor usability problem: it seems that Alt-Left ("Back") no longer works on the QC website after installing it.  I get no error in the JS console; it seems that the plugin is intercepting the "Left" key (which does go to the previous comic correctly).

I'm using Firefox 44.0.2 on Arch Linux x64.

**Comment by ilyvion** [comment]
I've tested and confirmed that this is a problem on Firefox. Works just fine on Chrome. I'll look into it as soon as I can. Thanks for your report. :)

**Comment by ilyvion** [comment]
The odd thing is that using the back button works. And if it is interception of the Left key that breaks it, then you'd think that it would cause the extension to navigate to the previous comic, right? I certainly don't check for which special keys (Alt/Ctrl/Shift/etc.) are pressed in that handler. Curious.

**Comment by thirtythreeforty** [comment]
Awesome! Thanks for the quick turnaround and resolution.

**Comment by ilyvion** [comment]
I'll try to get a new release out soon. :)
