### ISSUE TITLE
Editor code doesn't always stay

### ISSUE THREAD

**Issue by thejonpearson** [Questionable-Content-Extensions/client#3]
When moving between comics with data and comics without data, it doesn't look like the editor code is 'saved'. Obviously not a critical error, but a quality of life type thing.

Reproduction:

Enter editor code, make edit. Manually change URL to next comic (comic with no data entered). Attempt to edit new comic, receive error. Firefox 46.0.1 on mac.

**Comment by ilyvion** [comment]
Any settings changed are saved when the dialog is closed. So if you make a change/enter values, and don't close the dialog before causing a page refresh, changes will be lost.

I'll see if I can't make the experience better.

**Comment by thejonpearson** [comment]
I suppose what I must have been doing was clicking outside the settings dialogue, rather than the close button.  TBH, I didn't even see the close button until this morning. This may well be chalked up to user-error, but if there's a way to catch / save changes on 'any' close of the dialogue, rather than just the close button, that would probably be a quality-of-life improvement, at least :)

**Comment by ilyvion** [comment]
Nope, that's not user error. I see now after review that it only saves when the button is pressed. It was supposed to save when the dialog was closed by any means. I'll get it fixed.
