### ISSUE TITLE
Add option buttons next to cast members/locations to restrict navigation

### ISSUE THREAD

**Issue by Nixill** [Questionable-Content-Extensions/client#33]
For example, the selection panel could look like this:

![image](https://user-images.githubusercontent.com/1627071/60893237-9431d580-a22e-11e9-8dbe-127f03bcd04f.png)

And when a character or location is selected, the left and right arrows; or nav links at the top and bottom of the comic; and clicking the comic itself all navigate only between strips containing the selected character or location.

**Comment by ilyvion** [comment]
I was going to ask how this is different than just using the arrows on the character or location, but I think I get it -- you want this mechanism to take over/override the general navigation system when enabled, right?

**Comment by Nixill** [comment]
Correct.

As for disabling it, either there'd be a button at the top or bottom of the panel, or just click the same character's button again.

**Comment by ilyvion** [comment]
I may choose to do this differently than you have suggested, btw. I already have plans to add more features to the navigation panels (like for #19 and #20), and yours may interfere/clash with my plans, so I need to find a way to fit it all in while still being usable and looking good.

**Comment by ilyvion** [comment]
This feature will be in the next release (1.2); it ended up looking like this:
![image](https://github.com/Questionable-Content-Extensions/client/assets/767490/78726a13-88c7-43c9-9584-11026e1009d8)
