### ISSUE TITLE
Non-guest non-canon comic skip issue

### ISSUE THREAD

**Issue by Nixill** [Questionable-Content-Extensions/client#36]
If you have the "skip non-canon comics" option checked, the "skip guest comics" option is frozen. However, if it's checked, the setting of "skip non-canon comics" is ignored.

**Comment by ilyvion** [comment]
Yep, verified. Very odd.

**Comment by ilyvion** [comment]
I believe this is no longer an issue after the release of 1.0 based on my own testing; feel free to re-open the issue if it turns out I'm wrong.

**Comment by ilyvion** [comment]
Never mind; the behavior remains; I just hadn't tested correctly when closing. As an example of a case where it still fails is if you're on comic [3130](https://questionablecontent.net/view.php?comic=3130) and have both "Skip non-canon strips" and "Skip guest strips" enabled; it'll still take you to [3131](https://questionablecontent.net/view.php?comic=3131), a non-canon strip.
