### ISSUE TITLE
Greasemonkey chokes because icon files aren't on site

### ISSUE THREAD

**Issue by trlkly** [Questionable-Content-Extensions/client#44]
While I can edit the script to work around this, it doesn't let me enable automatic updates if I do that. 

I also note that you can't install from the releases page on Github. as it returns the wrong MIME type for .user.js files. 

Would it be too big a deal to just throw up a basic HTML page on the original site that just links to the extension installation? Or possibly put the extension up on one of the various userscript repositories? I know that openuserjs.org will link with Github (though I've only ever linked my account and the files, never releases.)

**Comment by ilyvion** [comment]
I do not plan on using a third party service for this, but I also don't think this will be a problem again for the foreseeable future, though I am only human and will surely mess up something again in the future. 😅
