### ISSUE TITLE
Database issues

### ISSUE THREAD

**Issue by trlkly** [Questionable-Content-Extensions/client#61]
Every time I load a page now, I get the following error:

> error communicating with database. Cannot assign requested address. (os error 99). 

I get the same error if I directly try to go to https://questionablextensions.net/api/comicdata/

**Comment by ilyvion** [comment]
Thanks; I noticed just about at the same time as you made this report, and now it's back up and running. 😄

**Comment by trlkly** [comment]
For curiosity's sake, what was the problem? What did you have to do to fix it?

**Comment by ilyvion** [comment]
I had made a snafu when I was updating my TLS/SSL updating job, so the certificate for the database server had expired. And then I further messed up when trying to fix it where I used a type of certificate that the database didn't support. So I fixed the updating job *and* the database certificate type, and then things started working again.
