### ISSUE TITLE
pool timeout again

### ISSUE THREAD

**Issue by trlkly** [Questionable-Content-Extensions/client#62]
Getting a pool timeout error when the extension tries to access the API. Full error is 

`pool timed out while waiting for an open connection`

I get the same error if I manually go to https://questionablextensions.net/api/comicdata/

**Comment by ilyvion** [comment]
Hi. Thanks for the report!

I was doing some server maintenance/security tightening, and I forgot to update the QCXT config after I was done. It's been working fine for about three hours at this point.

My apologies to anyone affected.
